name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  all:
    name: Tests all
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install npm modules
        run: yarn
      - name: Test
        run: yarn test